version: "3.9"

services:
  postgres:
    container_name: "n5project_postgres"
    image: "postgres:12.7-alpine"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: "always"

  project:
    container_name: "n5project_project"
    build: .
    expose:
      - "8000"
    depends_on:
      - "postgres"
    restart: "always"


volumes:
  postgres_data: {}
