version: "3.9"

services:
  postgres:
    container_name: "n5project_postgres"
    ports:
      - "5432:5432"

  project:
    container_name: "n5project_project"
    volumes:
      - ".:/opt/n5project"
    environment:
      DEBUG: "true"
    ports:
      - "8000:8000"
    command: >
      sh -c "poetry install
      && poetry run python manage.py makemigrations --noinput
      && poetry run python manage.py migrate --noinput
      && poetry run python manage.py runserver 0:8000"
